/*
* This file, too was autogenerated by Android Studio. It's kinda just here.
 */
package com.example.ics3u;

import android.os.Bundle;

import androidx.appcompat.app.AppCompatActivity;

public class EditPlannedMealView extends AppCompatActivity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_edit_planned_meal_view);
    }
}